function [mpc_bus] = get_bus_mpc(csv_file)
    mpc_bus_read = csvread(csv_file,2);
    mpc_bus_read_type = [mpc_bus_read(:,1),ones(size(mpc_bus_read,1),1),...
    mpc_bus_read(:,2:end)];
    mpc_bus = [mpc_bus_read_type(:,1:10), ...
        mpc_bus_read_type(:,11:end),1.1*ones(size(mpc_bus_read,1),1),...
        0.90*ones(size(mpc_bus_read,1),1)];