function [mpc_gencost] = get_gencost_mpc(csv_file)
mpc_gen_cost_read = csvread(csv_file,2);
mpc_gencost = [2*ones(size(mpc_gen_cost_read,1),1), zeros(size( ...
    mpc_gen_cost_read,1),2), 2*ones(size(mpc_gen_cost_read,1),1), ...
    mpc_gen_cost_read(:,1)/1e6,zeros(size(mpc_gen_cost_read,1),1)];